### ISSUE TITLE
Feature Request: Add Google Apps Domain Support

### ISSUE THREAD

**Issue by mikestecker** [dukt/oauth#20]
See the `hd` parameter:
https://developers.google.com/identity/protocols/OpenIDConnect#authenticationuriparameters

**Comment by carlcs** [comment]
Hey Mike, you can already connect with whatever authorization parameters you would like.

```php
$authorizationOptions = [
    'hd' => 'mycompany.com'
];
 
$response = craft()->oauth->connect([
    'plugin' => 'myPlugin',
    'provider' => $providerHandle,
    'scope' => $scope,
    'authorizationOptions' => $authorizationOptions
]);
```
Dukt Social can also be configured to override a providers default `authorizationOptions` via a social.php configuration file.

```php
return [
    'googleLoginProvider' => [
        'authorizationOptions' => [
            'hd' => 'mycompany.com'
        ],
    ],
];
```

**Comment by mikestecker** [comment]
perfect, thanks!

**Comment by mikestecker** [comment]
@carlcs hmm it's not working. I was still able to login with a different Google account even though I set up my social.php config file as you suggested:
![screenshot 2016-05-13 10 34 46](https://cloud.githubusercontent.com/assets/407465/15256459/73845958-18f6-11e6-97e8-5072c8b4152b.png)

I'd like to lock out anyone who is not a part of the domain that I have it locked to.

I'm using Dukt OAuth 1.0.79 and Social Login 1.0.12186401

**Comment by wfendler** [comment]
@mikestecker @carlcs any updates on this issue? I think I'm running into the same problem.

Just installed everything fresh and tried to limit it to our company's domain and I just got through with my Gmail account.

**Comment by benjamindavid** [comment]
The `hd` parameter only improves the UI for your domain but out of the box, it can't really be trusted for domain verification:
https://developers.google.com/identity/protocols/OpenIDConnect#hd-param

Social plugin has a `lockDomains` config setting that can be used for that matter:
https://dukt.net/social/docs/config-settings#lockDomains

**Comment by wfendler** [comment]
Hm, I've tried using that a few times.

Is this the correct placement? I'm unsure whether or not `lockDomains` is a "global" rule or if it's specific to each service.

```php
<?php

return array(
  'google' => [
    'userMapping' => [
      'firstName' => '{{ firstName }}',
      'lastName' => '{{ lastName }}',
    ],
    'lockDomains' => [
      'mydomain.com'
    ],
  ],
);

```

I've tried it in both places and it seems I can still log in with my personal gmail account.

Apologies if I'm discussing this issue in the wrong place. I can't seem to find the repo for the social plugin.

**Comment by wfendler** [comment]
Hm, I moved it to be a "global" rule outside of the google config and it seems to be working now! I must have been trying to many different configurations at once before when it wasn't working. 

Now the problem is that it's lacking errors. Is there documentation on errors for these templates? I see the social-demo repo and it has errors for profiles and password reset and whatnot but nothing about being denied access. Is this something that's available or is there some kind of hook I could get in the template to write my own error here?
