### ISSUE TITLE
Composer dukt/oauth2-vimeo package broken

### ISSUE THREAD

**Issue by gijsstegehuis** [dukt/oauth#24]
https://packagist.org/packages/dukt/oauth2-vimeo references repo https://github.com/dukt/oauth2-vimeo, but it no longer exists.

Composer installs fail because this package is now a  [dependency](https://github.com/dukt/craft-oauth/commit/e67c4be21b1e39a4dfc6828bf2a05e8859844c4d) of the main package.
Please update package repo reference, or remove the dependency from the project.

**Comment by benjamindavid** [comment]
This dependency has been replaced with https://github.com/saf33r/oauth2-vimeo. Thanks!
