### ISSUE TITLE
Twitter Fatal error and Facebook Parse error

### ISSUE THREAD

**Issue by MichaelLotriet** [dukt/oauth#27]
Hi,

I am trying to connect to Twitter and Facebook with the Dukt Facebook, Twitter and S. Group Social Poster plugins. 

I am using the following versions:
Craft: 2.6.2961
OAuth: 2.0.3
Facebook: 1.1.1
Twitter: 1.1.2
Social Poster: 1.2.0

**Every time I try and connect to Facebook with either plugin I get the following Parse error:**
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /home/onthewir/public_html/ra/craft/plugins/oauth/vendor/league/oauth2-client/src/Grant/GrantFactory.php on line 85

**And this is what the oauth.log records for Facebook**
2017/02/09 13:20:24 [info] [plugin] OAuth Connect - Connect with `facebook` OAuth provider
Session Data: Array
(
    [oauth.referer] => /ra/public/index.php/ra_admin/actions/facebook/connect
    [oauth.scope] => Array
        (
            [0] => public_profile
            [1] => manage_pages
            [2] => read_insights
        )

    [oauth.authorizationOptions] => Array
        (
        )

)

in /home/onthewir/public_html/ra/craft/app/etc/plugins/BasePlugin.php (65)
in /home/onthewir/public_html/ra/craft/plugins/oauth/controllers/OauthController.php (61)
in /home/onthewir/public_html/ra/craft/app/etc/web/WebApp.php (817)
2017/02/09 13:20:24 [info] [plugin] Redirect URI: http://onthewire.co.za/ra/public/index.php/actions/oauth/connect
in /home/onthewir/public_html/ra/craft/app/etc/plugins/BasePlugin.php (65)
in /home/onthewir/public_html/ra/craft/plugins/oauth/providers/BaseProvider.php (422)
in /home/onthewir/public_html/ra/craft/plugins/oauth/providers/Facebook.php (65)

**Every time I try and connect to Twitter with either plugin I get the following Fatal error:**
Fatal error: Call to undefined function GuzzleHttp\Handler\curl_reset() in /home/onthewir/public_html/ra/craft/plugins/oauth/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

**And this is what the oauth.log records for Twitter**
2017/02/09 13:22:30 [info] [plugin] Redirect to OAuth Connect
Redirect to: http://onthewire.co.za/ra/public/index.php/ra_admin/actions/oauth/connect?provider=twitter
Session Data: Array
(
    [oauth.referer] => /ra/public/index.php/ra_admin/actions/twitter/oauth/connect
    [oauth.scope] => Array
        (
        )

    [oauth.authorizationOptions] => Array
        (
        )

)

in /home/onthewir/public_html/ra/craft/app/etc/plugins/BasePlugin.php (65)
in /home/onthewir/public_html/ra/craft/plugins/oauth/services/OauthService.php (101)
in /home/onthewir/public_html/ra/craft/plugins/twitter/controllers/Twitter_OauthController.php (52)

**If i have dev mode disabled it just displays a white page and the following note in the developer tools:**
The character encoding of the HTML document was not declared. The document will render with garbled text in some browser configurations if the document contains characters from outside the US-ASCII range. The character encoding of the page must be declared in the document or in the transfer protocol.

**Comment by benjamindavid** [comment]
OAuth requires PHP 5.6+. Updating your PHP version should fix the issue.
