### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by strohrdanz** [dukt/oauth#28]
Getting this error when trying to connect with Google: 
```
Parse error: syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$' in /var/www/html/craft/plugins/oauth/vendor/league/oauth2-client/src/Grant/GrantFactory.php on line 85
```

in reference to this function: 
```
public function isGrant($class)
    {
        return is_subclass_of($class, AbstractGrant::class);
    }
```

**Comment by coryetzkorn** [comment]
Also experiencing this issue.

**Comment by benjamindavid** [comment]
Which PHP version are you guys using ? Please make sure that you are using PHP 5.6 or above.

**Comment by coryetzkorn** [comment]
That's probably it! Currently on 5.4.16. Will upgrade and report back.

**Comment by strohrdanz** [comment]
Definitely was my issue, I upgraded and it works. 
Thanks!
