### ISSUE TITLE
Multiple apps for the same provider

### ISSUE THREAD

**Issue by jamiepittock** [dukt/oauth#29]
Hi Ben

Is it possible to create multiple applications for the same provider?

Cheers
Jamie

**Comment by benjamindavid** [comment]
Not really, but if you just want to have different apps per environment, this is possible, just define the `providerInfos` config for each environment:
- https://dukt.net/oauth/docs/configuration
- https://craftcms.com/docs/multi-environment-configs

**Comment by jamiepittock** [comment]
No problem, Thanks for confirming.
