### ISSUE TITLE
Craft 3

### ISSUE THREAD

**Issue by EternalBlack** [dukt/oauth#38]
Are there any plans that this plugins will be ported to Craft 3? Also: if `yes`, will it remain free?

**Comment by benjamindavid** [comment]
No plans to port it to Craft 3. I encourage you to use the https://github.com/thephpleague/oauth2-client library to handle OAuth in your plugins. Here are a few examples of how we implemented it in our plugins for Craft 3:

- https://github.com/dukt/analytics
- https://github.com/dukt/facebook
- https://github.com/dukt/twitter
- https://github.com/dukt/videos
